import hoodie1 from "../../assets/womenCollection/hoodie/outwearhoodie1.avif";
import hoodie2 from "../../assets/womenCollection/hoodie/outwearhoodie2.avif";
import hoodie3 from "../../assets/womenCollection/hoodie/outwearhoodie3.avif";
import hoodie4 from "../../assets/womenCollection/hoodie/outwearhoodie4.avif";
import jacket1 from "../../assets/womenCollection/jackets/outwearjacket1.avif";
import jacket2 from "../../assets/womenCollection/jackets/outwearjacket2.avif";
import jacket3 from "../../assets/womenCollection/jackets/outwearjacket3.avif";
import jacket4 from "../../assets/womenCollection/jackets/outwearjacket4.avif";
import jacket5 from "../../assets/womenCollection/jackets/outwearjacket5.avif";
import jacket6 from "../../assets/womenCollection/jackets/outwearjacket6.avif";
import jacket7 from "../../assets/womenCollection/jackets/outwearjacket7.avif";
import jacket8 from "../../assets/womenCollection/jackets/outwearjacket8.avif";
import jacket9 from "../../assets/womenCollection/jackets/outwearjacket9.avif";
import jacket10 from "../../assets/womenCollection/jackets/outwearjacket10.avif";
import jacket11 from "../../assets/womenCollection/jackets/outwearjacket11.avif";
import coat1 from "../../assets/womenCollection/overcoat/outwearcoat1.avif";
import coat2 from "../../assets/womenCollection/overcoat/outwearcoat2.avif";
import coat3 from "../../assets/womenCollection/overcoat/outwearcoat3.avif";
import coat4 from "../../assets/womenCollection/overcoat/outwearcoat4.avif";
import coat5 from "../../assets/womenCollection/overcoat/outwearcoat5.avif";

const womenOutwearData = {
  Hoodies: [
    {
      image: hoodie1,
      colors: ["#3D3D3D", "#BFBFBF", "#A0A0A0"],
      category: "Women",
      size: "L , XXL",
      name: "Pufftech Parkha",
      price: "5,999",
      rating: 4.9,
      inStock: 37,
      link: "/search/women/outwear",
    },
    {
      image: hoodie2,
      colors: ["#5E5E5E", "#C8C8C8", "#9E9E9E"],
      category: "Women",
      size: "L , XL",
      name: "Seamless Down Parkha",
      price: "4,899",
      rating: 4.3,
      inStock: 78,
      link: "/search/women/outwear",
    },
    {
      image: hoodie3,
      colors: ["#4C4C4C", "#ECECEC", "#9D9D9D"],
      category: "Women",
      size: "L , XL , XXL",
      name: "UV Protection Down Parkha",
      price: "4,899",
      rating: 4.7,
      inStock: 28,
      link: "/search/women/outwear",
    },
    {
      image: hoodie4,
      colors: ["#000000", "#FFFFFF", "#FF5733"],
      category: "Women",
      size: "L , XL",
      name: "UV Protection Down Parkha",
      price: "2,999",
      rating: 4.1,
      inStock: 119,
      link: "/search/women/outwear",
    },
  ],
  Jackets: [
    {
      image: jacket1,
      colors: ["#464646", "#CDCDCD", "#7F7F7F"],
      category: "Women",
      size: "L",
      name: "Fluffy Yarn",
      price: "2,799",
      rating: 4.6,
      inStock: 54,
      link: "/search/women/outwear",
    },
    {
      image: jacket2,
      colors: ["#292929", "#D9D9D9", "#767676"],
      category: "Women",
      size: "L , XL",
      name: "Fluffy Yarn",
      price: "2,999",
      rating: 4.6,
      inStock: 19,
      link: "/search/women/outwear",
    },
    {
      image: jacket3,
      colors: ["#121212", "#C3C3C3", "#505050"],
      category: "Women",
      size: "L , XXL",
      name: "Down Jacket",
      price: "3,999",
      rating: 4.1,
      inStock: 16,
      link: "/search/women/outwear",
    },
    {
      image: jacket4,
      colors: ["#363636", "#EAEAEA", "#7A7A7A"],
      category: "Women",
      size: "L , XXXL , XXL",
      name: "Down Vest",
      price: "7,99",
      rating: 4.6,
      inStock: 23,
      link: "/search/women/outwear",
    },
    {
      image: jacket5,
      colors: ["#121212", "#BFBFBF", "#A1A1A1"],
      category: "Women",
      size: "L , XL , XXL",
      name: "Puff Relaxed Jacket",
      price: "7,999",
      rating: 4.9,
      inStock: 56,
      link: "/search/women/outwear",
    },
    {
      image: jacket6,
      colors: ["#4A4A4A", "#F2F2F2", "#8B8B8B"],
      category: "Women",
      size: "L , XL , XXL",
      name: "Stripped Jacket",
      price: "2,899",
      rating: 4.8,
      inStock: 59,
      link: "/search/women/outwear",
    },
    {
      image: jacket7,
      colors: ["#363636", "#EAEAEA", "#7A7A7A"],
      category: "Women",
      size: "L, XXL",
      name: "Short Jacket",
      price: "3,666",
      rating: 4.1,
      inStock: 7,
      link: "/search/women/outwear",
    },
    {
      image: jacket8,
      colors: ["#292929", "#D9D9D9", "#767676"],
      category: "Women",
      size: "L , XL",
      name: "Jersey Jacket",
      price: "3,0000",
      rating: 4.9,
      inStock: 90,
      link: "/search/women/outwear",
    },
    {
      image: jacket9,
      colors: ["#3E3E3E", "#CFCFCF", "#888888"],
      category: "Women",
      size: "L , XL ",
      name: "Short Jacket",
      price: "9,000",
      rating: 4.8,
      inStock: 57,
      link: "/search/women/outwear",
    },
    {
      image: jacket10,
      colors: ["#121212", "#BFBFBF", "#A1A1A1"],
      category: "Women",
      size: "L , XL, XXL",
      name: "Cozy Jaclet",
      price: "5,999",
      rating: 3.8,
      inStock: 89,
      link: "/search/women/outwear",
    },
    {
      image: jacket11,
      colors: ["#505050", "#F6F6F6", "#9A9A9A"],
      category: "Women",
      size: "L , XL , XXXL",
      name: "Buppy Jacket",
      price: "3,299",
      rating: 4.7,
      inStock: 6,
      link: "/search/women/outwear",
    },
  ],
  Coats: [
    {
      image: coat1,
      colors: ["#505050", "#F6F6F6", "#9A9A9A"],
      category: "Women",
      size: "L , XL , XXXL",
      name: "Hybrid Down Coat",
      price: "5,999",
      rating: 4.6,
      inStock: 63,
      link: "/search/women/outwear",
    },
    {
      image: coat2,
      colors: ["#000000", "#FFFFFF", "#FF5733"],
      category: "Women",
      size: " XL ,XXL,  XXXL",
      name: "Coat Reflexed Fit",
      price: "3,888",
      rating: 4.7,
      inStock: 61,
      link: "/search/women/outwear",
    },
    {
      image: coat3,
      colors: ["#333333", "#C7C7C7", "#888888"],
      category: "Women",
      size: "L , XL , XXXL",
      name: "Non-Quilled Coat",
      price: "3,999",
      rating: 4.2,
      inStock: 22,
      link: "/search/women/outwear",
    },
    {
      image: coat4,
      colors: ["#464646", "#CDCDCD", "#7F7F7F"],
      category: "Women",
      size: "XL, XXL , XXXL",
      name: "UZ Coat",
      price: "8,999",
      rating: 4.7,
      inStock: 90,
      link: "/search/women/outwear",
    },
    {
      image: coat5,
      colors: ["#121212", "#C3C3C3", "#505050"],
      category: "Women",
      size: "L , XL , XXXL",
      name: "Long Coat",
      price: "6,888",
      rating: 4.9,
      inStock: 34,
      link: "/search/women/outwear",
    },
  ],
};

export default womenOutwearData;
