import bag1 from "../../assets/womenCollection/accessories/bag/accessoriesBag1.avif";
import bag2 from "../../assets/womenCollection/accessories/bag/accessoriesBag2.avif";
import bag3 from "../../assets/womenCollection/accessories/bag/accessoriesBag3.avif";
import bag4 from "../../assets/womenCollection/accessories/bag/accessoriesBag4.avif";
import bag5 from "../../assets/womenCollection/accessories/bag/accessoriesBag5.avif";
import bag6 from "../../assets/womenCollection/accessories/bag/accessoriesBag6.avif";
import bag7 from "../../assets/womenCollection/accessories/bag/accessoriesBag7.avif";
import bag8 from "../../assets/womenCollection/accessories/bag/accessoriesBag8.avif";
import bag9 from "../../assets/womenCollection/accessories/bag/accessoriesBag9.avif";
import bag10 from "../../assets/womenCollection/accessories/bag/accessoriesBag10.avif";
import bag11 from "../../assets/womenCollection/accessories/bag/accessoriesBag11.avif";
import bag12 from "../../assets/womenCollection/accessories/bag/accessoriesBag12.avif";
import belt1 from "../../assets/womenCollection/accessories/belt/accessoriesBelt1.avif";
import belt2 from "../../assets/womenCollection/accessories/belt/accessoriesBelt2.avif";
import belt3 from "../../assets/womenCollection/accessories/belt/accessoriesBelt3.avif";
import belt4 from "../../assets/womenCollection/accessories/belt/accessoriesBelt4.avif";
import belt5 from "../../assets/womenCollection/accessories/belt/accessoriesBelt5.avif";
import belt6 from "../../assets/womenCollection/accessories/belt/accessoriesBelt6.avif";
import belt7 from "../../assets/womenCollection/accessories/belt/accessoriesBelt7.avif";
import hat1 from "../../assets/womenCollection/accessories/hat/accessoriesHat1.avif";
import hat2 from "../../assets/womenCollection/accessories/hat/accessoriesHat2.avif";
import hat3 from "../../assets/womenCollection/accessories/hat/accessoriesHat3.avif";
import hat4 from "../../assets/womenCollection/accessories/hat/accessoriesHat4.avif";
import hat5 from "../../assets/womenCollection/accessories/hat/accessoriesHat5.avif";
import hat6 from "../../assets/womenCollection/accessories/hat/accessoriesHat6.avif";
import hat7 from "../../assets/womenCollection/accessories/hat/accessoriesHat7.avif";
import hat8 from "../../assets/womenCollection/accessories/hat/accessoriesHat8.avif";

const menAccessories = {
  Bag: [
    {
      image: bag1,
      colors: ["#3D3D3D", "#BFBFBF", "#A0A0A0"],
      category: "Men",
      size: "L , XL, XXL",
      name: "Rounded Mini Bag",
      price: "1,490",
      rating: 4.6,
      inStock: 34,
      link: "/search/men/accessories",
    },
    {
      image: bag2,
      colors: ["#2E8B57", "#FFF8DC", "#556B2F"],
      category: "Men",
      size: "L , XL, XXL",
      name: "Packable Bag",
      price: "1,990",
      rating: 4.2,
      inStock: 18,
      link: "/search/men/accessories",
    },
    {
      image: bag3,
      colors: ["#000080", "#87CEFA", "#4682B4"],
      category: "Men",
      size: "L , XL, XXXL",
      name: "2Way Shoulder Bag",
      price: "2,999",
      rating: 3.9,
      inStock: 11,
      link: "/search/men/accessories",
    },
    {
      image: bag4,
      colors: ["#FFD700", "#FFA500", "#FF6347"],
      category: "Men",
      size: "L , XXL , XXL",
      name: "Rounded Mini Bag",
      price: "2,789",
      rating: 4.6,
      inStock: 23,
      link: "/search/men/accessories",
    },
    {
      image: bag5,
      colors: ["#A52A2A", "#D2B48C", "#8B4513"],
      category: "Men",
      size: "L , XXL, XXL",
      name: "KAWS + Warhol 2 Way Bag",
      price: "1,990",
      rating: 4.3,
      inStock: 78,
      link: "/search/men/accessories",
    },
    {
      image: bag6,
      colors: ["#708090", "#D3D3D3", "#2F4F4F"],
      category: "Men",
      size: "L , XXL , XXXL",
      name: "Crossbody Bag",
      price: "1,990",
      rating: 4.3,
      inStock: 34,
      link: "/search/men/accessories",
    },
    {
      image: bag7,
      colors: ["#800080", "#DA70D6", "#D8BFD8"],
      category: "Men",
      size: "L , XL , XXL",
      name: "Reusable Bag",
      price: "250",
      rating: 5.0,
      inStock: 8,
      link: "/search/men/accessories",
    },
    {
      image: bag8,
      colors: ["#696969", "#808080", "#A9A9A9"],
      category: "Men",
      size: "L , XL, XXL",
      name: "Gift Bag",
      price: "250",
      rating: 4.1,
      inStock: 38,
      link: "/search/men/accessories",
    },
    {
      image: bag9,
      colors: ["#FFFAFA", "#FFE4E1", "#CD5C5C"],
      category: "Men",
      size: "L, XL, XXL",
      name: "Iron Paper Bag",
      price: "1,990",
      rating: 4.3,
      inStock: 13,
      link: "/search/men/accessories",
    },
    {
      image: bag10,
      colors: ["#1C1C1C", "#A9A9A9", "#FAFAFA"],
      category: "Men",
      size: "L , XL, XXL",
      name: "Drawsting Bag",
      price: "1998",
      rating: 4.1,
      inStock: 18,
      link: "/search/men/accessories",
    },
    {
      image: bag11,
      colors: ["#FF5733", "#FFC300", "#DAF7A6"],
      category: "Men",
      size: "L , XXL",
      name: "Faux Leather Bag",
      price: "1,490",
      rating: 4.7,
      inStock: 18,
      link: "/search/men/accessories",
    },
    {
      image: bag12,
      colors: ["#333333", "#C7C7C7", "#888888"],
      category: "Men",
      size: "L , XXL",
      name: "Rounded Mini Bag",
      price: "990",
      rating: 4.5,
      inStock: 37,
      link: "/search/men/accessories",
    },
  ],
  Belt: [
    {
      image: belt1,
      colors: ["#333333", "#C7C7C7"],
      category: "Men",
      size: "",
      name: "Vintage Belt",
      price: "1,990",
      rating: 4.2,
      inStock: 4,
      link: "/search/men/accessories",
    },
    {
      image: belt2,
      colors: ["#888888"],
      category: "Men",
      size: "",
      name: "Clean Belt",
      price: "1,499",
      rating: 4.8,
      inStock: 13,
      link: "/search/men/accessories",
    },
    {
      image: belt3,
      colors: ["#333333", "#C7C7C7", "#333333"],
      category: "Men",
      size: "",
      name: "Clean Leather Belt",
      price: "2,199",
      rating: 4.2,
      inStock: 42,
      link: "/search/men/accessories",
    },
    {
      image: belt4,
      colors: ["#C7C7C7", "#888888"],
      category: "Men",
      size: "",
      name: "Mesh Long Belt",
      price: "1,990",
      rating: 4.7,
      inStock: 37,
      link: "/search/men/accessories",
    },
    {
      image: belt5,
      colors: ["#333333", "#C7C7C7", "#888888"],
      category: "Men",
      size: "",
      name: "Leather Combination Mesh Belt",
      price: "1,990",
      rating: 4.9,
      inStock: 78,
      link: "/search/men/accessories",
    },
    {
      image: belt6,
      colors: ["#333333", "#C7C7C7", "#888888"],
      category: "Men",
      size: "",
      name: "Dress Skinny Belt",
      price: "1,990",
      rating: 5.0,
      inStock: 7,
      link: "/search/men/accessories",
    },
    {
      image: belt7,
      colors: ["#333333", "#C7C7C7", "#888888"],
      category: "Men",
      size: "",
      name: "Italian Belt",
      price: "990",
      rating: 4.9,
      inStock: 23,
      link: "/search/men/accessories",
    },
  ],
  Hat: [
    {
      image: hat1,
      colors: ["#333333", "#C7C7C7", "#888888"],
      category: "Men",
      size: "",
      name: "Italian Cap",
      price: "990",
      rating: 4.4,
      inStock: 6,
      link: "/search/men/accessories",
    },
    {
      image: hat2,
      colors: ["#333333", "#C7C7C7", "#888888"],
      category: "Men",
      size: "",
      name: "Cactus Cap",
      price: "1,290",
      rating: 4.3,
      inStock: 20,
      link: "/search/men/accessories",
    },
    {
      image: hat3,
      colors: ["#333333", "#C7C7C7", "#888888"],
      category: "Men",
      size: "",
      name: "Cashmere Cap",
      price: "499",
      rating: 4.0,
      inStock: 76,
      link: "/search/men/accessories",
    },
    {
      image: hat4,
      colors: ["#333333", "#C7C7C7", "#888888"],
      category: "Men",
      size: "",
      name: "2Way Cap",
      price: "1,200",
      rating: 4.9,
      inStock: 9,
      link: "/search/men/accessories",
    },
    {
      image: hat5,
      colors: ["#333333", "#C7C7C7", "#888888"],
      category: "Men",
      size: "",
      name: "Fluffy Cap",
      price: "1,200",
      rating: 3.8,
      inStock: 23,
      link: "/search/men/accessories",
    },
    {
      image: hat6,
      colors: ["#333333", "#C7C7C7", "#888888"],
      category: "Men",
      size: "",
      name: "Uv Cap",
      price: "799",
      rating: 4.1,
      inStock: 10,
      link: "/search/men/accessories",
    },
    {
      image: hat7,
      colors: ["#333333", "#C7C7C7", "#888888"],
      category: "Men",
      size: "",
      name: "Padded Hat",
      price: "780",
      rating: 3.9,
      inStock: 78,
      link: "/search/men/accessories",
    },
    {
      image: hat8,
      colors: ["#333333", "#C7C7C7", "#888888"],
      category: "Men",
      size: "",
      name: "Paddy Hat",
      price: "1,100",
      rating: 4.3,
      inStock: 9,
      link: "/search/men/accessories",
    },
  ],
};

export default menAccessories;
